### PR TITLE
Add Preferences dialog to allow switching display panel

### PR DESCRIPTION
**Pull request by bittner**
We want to allow users to have the reStructuredText preview rendered in the side panel or the bottom panel, at their option.

This is a follow-up on #16, cc @JanKanis.

### CODE REVIEW

**Comment by bittner** [comment]
@JanKanis How did you manage to use the side panel?

I simply do a call to `window.get_side_panel()`, but this totally cripples GEdit.

- The document doesn't display in the side bar.
- The `☰` ➜ `View ▸` menu stops having a `☐ Bottom Panel` menu item.

I have to use `dconf-editor` and reset `org.gnome.gedit.state.window bottom-panel-active-page` to get the View menu back to normal.

Any hints?

**Comment by JanKanis** [comment]
I simply replaced `window.get_bottom_panel()` by `window.get_side_panel()` indeed. The preview then becomes an additional 'tab' in the side panel that can be selected. The bottom panel is hidden in the menu if there is nothing to show there. If you enable a different plugin that uses it (e.g. python console) it should become visible again in the view menu.

**Comment by bittner** [comment]
Could you try whether the implementation of this branch works for you (as in "as expected")?

**Comment by bittner** [comment]
Cool, I figured out where the panel is hidden! :see_no_evil: 

image

So, this _does_ work. I now only need to move the rendering container between the two panels when the selection changes in the Preferences dialog. :relieved:

**Comment by bittner** [comment]
This works reliably now, but gedit needs to be restarted to bring changed preferences into effect.

Merging now for easier, clearer communication on the code with the GNOME people.

**Pull request merged**
